#pragma once

#include <functional>
#include "esphome/core/component.h"
#include "esphome/core/log.h"
#include "esphome/components/climate/climate.h"
#include "esphome/components/number/number.h"
#include "../espresso_machine/interfaces.h"

namespace esphome {
namespace espresso_machine_heater {

// ---------------------------------------------------------------------------
// Forward declaration
// ---------------------------------------------------------------------------
class EspressoMachineHeater;

// ---------------------------------------------------------------------------
// SsrPeriodNumber — number entity that exposes the slow_pwm SSR period (ms)
// to Home Assistant at runtime, allowing users to adjust PID responsiveness
// without reflashing.  Lower period = faster SSR switching = more responsive
// PID output; higher period = less SSR wear.
// ---------------------------------------------------------------------------
class SsrPeriodNumber : public number::Number {
 public:
  void set_parent(EspressoMachineHeater *parent) { parent_ = parent; }

 protected:
  void control(float value) override;

  EspressoMachineHeater *parent_{nullptr};
};

// ---------------------------------------------------------------------------
// EspressoMachineHeater — production IHeater adapter for ESPHome climate.pid
//
// Wraps any ESPHome climate entity (typically climate.pid) and exposes it
// through the IHeater interface used by the EspressoMachine orchestrator.
//
// Usage in YAML:
//   espresso_machine_heater:
//     id: brew_heater_ctrl
//     climate_id: main_heater
//     ssr_output: heater_ssr          # optional — enables HA-adjustable SSR period
//     ssr_period_number:              # optional — HA number entity for SSR period (ms)
//       name: "SSR Period"
//
//   espresso_machine:
//     brew:
//       heater_controller: brew_heater_ctrl
//     steam:
//       heater_controller: brew_heater_ctrl
// ---------------------------------------------------------------------------
class EspressoMachineHeater : public Component,
                              public espresso_machine::IHeater {
 public:
  void set_climate(climate::Climate *climate) { climate_ = climate; }

  // Configures how close the current temperature must be to the target before
  // the heater is considered "ready" (i.e. the machine may proceed to brewing
  // or steaming).  A tolerance of 0.5°C means 89.5°C is ready when the target
  // is 90.0°C — preventing an indefinite wait when the thermoblock stabilises
  // just below the setpoint.  Defaults to 0.5°C.
  void set_temperature_tolerance(float tolerance) { temperature_tolerance_ = tolerance; }

  // SSR period control — called by SsrPeriodNumber::control() when the HA
  // number entity is changed.  Invokes the registered callback (set via
  // set_ssr_period_callback()) which calls set_period() on the slow_pwm output.
  void set_ssr_period_ms(uint32_t ms) {
    ssr_period_ms_ = ms;
    if (ssr_period_callback_)
      ssr_period_callback_(ms);
  }

  // Registers the callback that updates the underlying slow_pwm output period.
  // Generated by Python to_code() when ssr_output: is configured.
  void set_ssr_period_callback(std::function<void(uint32_t)> callback) {
    ssr_period_callback_ = std::move(callback);
  }

  // Wires the optional HA number entity for runtime SSR period adjustment.
  void set_ssr_period_number(SsrPeriodNumber *n) { ssr_period_number_ = n; }

  // Read-back accessor used by the display component.
  SsrPeriodNumber *get_ssr_period_number() const { return ssr_period_number_; }

  // Sets the default SSR period (ms) published to HA on boot.
  void set_ssr_default_period_ms(uint32_t ms) { ssr_period_ms_ = ms; }

  // IHeater — temperature reading
  float get_current_temperature() const override {
    return climate_ ? climate_->current_temperature : 0.0f;
  }

  // IHeater — readiness check.  Returns true when the current temperature is
  // within `temperature_tolerance_` degrees of the target in BOTH directions.
  // This prevents the machine from waiting indefinitely for a thermoblock that
  // has stabilised slightly below the setpoint (e.g. 89.9°C when target is
  // 90.0°C with a 0.5°C tolerance) while also returning false when the block
  // is significantly above the setpoint — ensuring cooldown gating works correctly.
  bool is_ready(float target_temp) const override {
    float current = get_current_temperature();
    return current >= (target_temp - temperature_tolerance_) &&
           current <= (target_temp + temperature_tolerance_);
  }

  // IHeater — above-target check.  Returns true when the current temperature
  // exceeds the target by more than `temperature_tolerance_`, indicating that
  // active cooling (pump + purge valve) is needed before brewing.
  bool is_above_target(float target_temp) const override {
    return get_current_temperature() > (target_temp + temperature_tolerance_);
  }

  // IHeater — setpoint command.
  // Also re-activates HEAT mode so that a previous force_off() (e.g. from
  // machine_off() or an over-temperature safety cutoff that was subsequently
  // cleared) does not leave the PID climate in OFF mode.
  void set_target_temperature(float t) override {
    if (climate_ == nullptr)
      return;
    auto call = climate_->make_call();
    call.set_mode(climate::CLIMATE_MODE_HEAT);
    call.set_target_temperature(t);
    call.perform();
  }

  // IHeater — force heater off (safety cutoff)
  void force_off() override {
    if (climate_ == nullptr)
      return;
    auto call = climate_->make_call();
    call.set_mode(climate::CLIMATE_MODE_OFF);
    call.perform();
  }

  void setup() override {
    ESP_LOGI("espresso_machine_heater", "EspressoMachineHeater adapter initialized");
    if (ssr_period_number_ != nullptr)
      ssr_period_number_->publish_state(static_cast<float>(ssr_period_ms_));
  }

  void loop() override {}

 protected:
  climate::Climate *climate_{nullptr};
  float temperature_tolerance_{0.5f};  // °C below target still considered "ready"

  // SSR period control (optional)
  uint32_t ssr_period_ms_{1000};  // ms — published to HA on boot; updated by number entity
  std::function<void(uint32_t)> ssr_period_callback_{nullptr};
  SsrPeriodNumber *ssr_period_number_{nullptr};
};

}  // namespace espresso_machine_heater
}  // namespace esphome
